# Constants

INTRODUCTION = """Welcome to Midnight Rider

WE'VE STOLEN A CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.


THAT'S WHY THE GOVERNMENT WANTS IT.

WE CAN'T LET THEM HAVE IT

ONE GOAL SURVIVAL... AND THE CAR
REACH THE SAFE HOUSE BEFORE THE MAN
GON GETCHU.


"""

CHOICES = """
    ---Your choices---
    A. Eat chips. 
    B. Travel slowly
    C. Speed ahead at full speed   
    D. Stop to refuel
    E. Check your current Status 
    Q. Quit the game.
    ---

"""

REFUEL = """-------You filled the fuel tank.
-------The agents got closer...
"""

EAT_CHIPS = """"----------Mmmmmmmmm, the saltiness of the chips is nice.
----------Your hunger is sated. 
"""

NO_CHIPS = """------ You have no chips left. :(
"""

SEVERE_HUNGER = """****** You stomach rumbles
****** You need to eat something quick
"""

HUNGER = """****** You're hungry, but not that hungry 
"""

ENDGAME_TEXT = [
    """\n\nThe game has ended. Thanks for playing""",  # quit game
    """\n\nTHE AGENTS HAVE CLOSED IN ON YOU.
THERE ARE AT LEAST 20 CARS SURROUNDING YOU.
THE LEAD CAR  BUMPS YOUR PASSENGER SIDE.
YOU MANAGE TO CORRECT YOUR STEERING
TO KEEP YOU FROM CRASHING


YOU DIDN'T SEE THE AGENT'S CAR RIGHT BESIDE YOU.
THAT DRIVER BUMPED YOUR CAR
AND THAT'S IT

YOU SPIN UNCONTROLLABLY
YOUR CAR FLIPS OVER AT LEAST TWO TIMES
OR MORE... YOU SEEM TO HAVE LOSE COUNT

SIRENS.

"ARE THEY ALIVE? THEY SAY AS YOU HEAR
FOOTSTEPS COMING CLOSER.
"DOESN'T MATTER, ALL WE WANTED WAS THE CAR."

YOU SEE A DOG SLOWLY STEP OUT OF THE 
OVERTURNED CAR.

"YOU WILL NEVER STOP THE REVOLUTION!"
THE DOG SEEMS TO SAY TO THE AGENTS.

IT WAS IN THE CAR THE WHOLE TIME

YOU DRIFT OFF INTO UNCOUNSCIOUSNESS...

-GAME END-----\n""",    # Lose - agents have caught up
    """\n\nYOUR CAR SPUTTERS AND SEEMS TO LET OUT
A BIG SIGH, THERE'S NO MORE FUEL LEFT.

THE AGENTS SURROUND YOU AND STEP OUT
OF THEIR CAR. THE LEAD AGENT RIPS
THE DOOR OPEN AND THROWS YOU OUT OF
YOUR CAR.

"WE FINALLY GOT IT."

YOU FAILED. 

------GAME END-----\n""",  # lose because of no fuel

    """\n\nYOUR STOMACH IS EMPTY. 
WHO KNEW THAT WHAT THE DOCTOR SAID WAS TRUE,
THAT HUMAN/ROBOT HYBRIDS WOULD NEED
CHIPS TO SUSTAIN THEMSELVES.
YOUR ROBOT SYSTEMS START TO SHUT DOWN.
YOUR HUMAN EYES CLOSE.
THE LAST THING THAT YOU HEAR ARE SIRENS.
THEY GOTCHU. THEY GOT THE CAR.
WE FAILED...  # lose because of too hungry
----GAME OVER"""
    """\n\nYOU PRESSED THE BUTTON TO OPEN THE GATE.
THIS ISN'T THE FIRST TIME YOU HAVE DONE THIS.
YOU CNA TIME IT PERFECTLY 
SO THAT YOU CAN SLIDE THE CAR IN AS THE GATE CLOSE

YOU KNOW YOU DID THE RIGHT THING.
THE GOVERNMENT WOULD HAVE TORN THE CAR APART.
ANALYZING IT, TESTING IT, AND DESTROYING IT.

THEY DON'T KNOW IT'S SECRETS...
THAT IT HOLD THE KEY TO DIFFERENT WORLDS.

AS YOU STEP OUT OF THE VEHICLE, FIDO RUNS
UP TO YOU

"THANK YOU FOR SAVING ME," HE SAYS.

AS YOU TAKE A COUPLE OF STEPS AWAY FROM THE CAR,
IT MAKES A STRANGE NOISE.

BEFORE YOUR EYES, IT SHIFTS ITS SHAPE.
YOU HAVE SEEN THIS BEFORE, BUT ONLY IN
THE MOVIES.

""BUMBLEBEE...?

----GAME OVER--- 
""",
]

REFILL_CHIPS = """******** look at your chips bag
*******It is filled magically
*****"you're welcome!" says a small voice.
******The dog used its magic chips cooking skills.\n"""